/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedUserCodeMappingRouteImport } from './routes/_authed/user-code-mapping'
import { Route as AuthedSupplierColumnMappingRouteImport } from './routes/_authed/supplier-column-mapping'
import { Route as AuthedImportRouteImport } from './routes/_authed/import'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUserCodeMappingRoute = AuthedUserCodeMappingRouteImport.update({
  id: '/user-code-mapping',
  path: '/user-code-mapping',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSupplierColumnMappingRoute =
  AuthedSupplierColumnMappingRouteImport.update({
    id: '/supplier-column-mapping',
    path: '/supplier-column-mapping',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedImportRoute = AuthedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/import': typeof AuthedImportRoute
  '/supplier-column-mapping': typeof AuthedSupplierColumnMappingRoute
  '/user-code-mapping': typeof AuthedUserCodeMappingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/import': typeof AuthedImportRoute
  '/supplier-column-mapping': typeof AuthedSupplierColumnMappingRoute
  '/user-code-mapping': typeof AuthedUserCodeMappingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/import': typeof AuthedImportRoute
  '/_authed/supplier-column-mapping': typeof AuthedSupplierColumnMappingRoute
  '/_authed/user-code-mapping': typeof AuthedUserCodeMappingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/import'
    | '/supplier-column-mapping'
    | '/user-code-mapping'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/import'
    | '/supplier-column-mapping'
    | '/user-code-mapping'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/import'
    | '/_authed/supplier-column-mapping'
    | '/_authed/user-code-mapping'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/user-code-mapping': {
      id: '/_authed/user-code-mapping'
      path: '/user-code-mapping'
      fullPath: '/user-code-mapping'
      preLoaderRoute: typeof AuthedUserCodeMappingRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/supplier-column-mapping': {
      id: '/_authed/supplier-column-mapping'
      path: '/supplier-column-mapping'
      fullPath: '/supplier-column-mapping'
      preLoaderRoute: typeof AuthedSupplierColumnMappingRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/import': {
      id: '/_authed/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthedImportRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedImportRoute: typeof AuthedImportRoute
  AuthedSupplierColumnMappingRoute: typeof AuthedSupplierColumnMappingRoute
  AuthedUserCodeMappingRoute: typeof AuthedUserCodeMappingRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedImportRoute: AuthedImportRoute,
  AuthedSupplierColumnMappingRoute: AuthedSupplierColumnMappingRoute,
  AuthedUserCodeMappingRoute: AuthedUserCodeMappingRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
